export const siteConfig = {
    brandName: "HL Korut",
    designerName: "Heli Lampi",
    initials: "HL",
    contestName: "Vuoden Koru 2026",
    contestFinalist: "Finalisti",
    location: "Oulu, Finland",
    email: "helilampi@icloud.com",
    phone: "+358 44 343 7802",
    instagramHandle: "@h.l.korut",
    instagramUrl: "https://www.instagram.com/h.l.korut",
    facebookUrl: "https://www.facebook.com/people/Heli-Lampi/61561959849448/#",
    tiktokUrl: "https://www.tiktok.com/@h.l.korut?_r=1&_t=ZN-91cUxnewSUI",
    profession: "Jalometallialan artesaani | Kultaseppäopiskelija",
    slogan: "Muotoilu, joka puhuttelee. Käsityö, joka kestää.",
    description: "Täplät-korusarja on valittu Vuoden Koru 2026 -finalistiksi. Vuoden Koru -finaalipaikka on osoitus tinkimättömästä laadusta ja taiteellisesta näkemyksestä.",
    metaTitle: "Heli Lampi | Vuoden Koru 2026 Finalisti | Täplät-korusarja",
    metaDescription: "Tutustu Heli Lammen Vuoden Koru 2026 -finaalikoruun. Uniikkia suomalaista korumuotoilua.",
    footerBrand: "HL Korut",
    footerDesigner: "Heli Lampi Design",
    copyright: "© 2025 HL Korut. All rights reserved."
};